# Generated by Django 4.2.9 on 2024-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='log_require',
            field=models.BooleanField(default=False),
        ),
    ]
