# Generated by Django 4.2.9 on 2024-03-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_log_require_post_log_require'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='log_require',
            new_name='login_require',
        ),
    ]
